#!/usr/bin/env bash

# Check if a virtual environment exists, else default to PATH python3
VENV_PYTHON="./.venv/bin/python3"
if [ -f "$VENV_PYTHON" ]; then
    PYTHON_EXEC="$VENV_PYTHON"
else
    PYTHON_EXEC="python3"
fi

# echo "Using: $PYTHON_EXEC"

FOLDER="$(dirname "$0")"
PARENT="$(dirname "$FOLDER")"

$PYTHON_EXEC "$PARENT"/src/aspeo.py "$@"
