# ASPeo PARAMETER FILE V0.0.1
[aspeo]
name = "Name"
description = "Desc"
output = "Out"
src_prefix = "pp_"
src_suffix = "_ss.tif"

[[source]]
id = "20250526"
#mp = "img1"
cam = "1.DIM"
#raw

[[source]]
id = "20210526"
#mp = "img2"
# cam = "2.DIM"

[stereo]
pairs = "example/pairs.txt"

[stereo.cmd]
session-type = "pinhole"
individually-normalize = true
alignment-method = "none"
threads-multiprocess = 5
process = 5
no-bigtiff = true
tif-compress = "Deflate"
corr-kernel = [21, 21]
cost-mode = 2
stereo-algorithm = "asp_bm"
subpixel-mode = 2
subpixel-kernel = [35, 35]
stop-point = 5

[corr-eval]
