[project]
name = "aspeo"
version = "0.2.0"
description = "Ames Stereo Pipeline (ASP) Sequential Workflows for Earth Observation"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "docopt>=0.6.2",
    "numpy>=2.3.1",
    "tomli>=2.2.1",
]
