name = "Envisat preset (4x8)"
description = "Preset to get started with full resolution Envisat images"
output = "."
src-folder = "./GEOTIFF/"
mp-suffix = ".VV.mod_log.tif"
pairs = "./PAIRS/table_pairs.txt"
pairs-header = true

[stereo]
t = "pinhole"
alignment-method = "none"
threads-multiprocess = 5
process = 5
stereo-algorithm = "asp_bm"
cost-mode = 2
subpixel-mode = 2
corr-kernel = [43, 87]
subpixel-kernel = [49, 99]
corr-search = [-5, -5, 5, 5]
individually-normalize = true
stop-point = 5
# The next two can improve the result to a small extent
rm-quantile-multiple = 1.6
prefilter-kernel-width = 1.8

[corr-eval]
