name = "Name"
description = "Desc"
output = "."
dem = ""
# source other than id > -prefix -suffix
# source = "smthg"
# source-header = true
pairs = "pairs.txt"
pairs-header = true
derive-pan = false
mp-pan = 0.7
mp-ms = 2

[[source]]
id = "id src" # ["id1", "id2"]
pan = ""
cam = ""
ms = ""
cam-ms = ""
mp = ""
pleiades = ""

# bundle_adjust > [MP]
[bundle-adjust] # BA

# mapproject > [MP]
[map-project] # MP/PAN / MP/MS

# gdal_translate > [MP]
[crop] # CROP

# gdal_pansharpening.py > [MP]
[pansharpening] # PANSHARP

# orbitviz > [MP]
[orbitviz] # ORB

# image_align > [PT]
[image-align] # ALIGNED

# parallel_stereo > [PT / DSM]
[stereo] # STEREO > PAIR

# corr_eval > [PT]
[corr-eval] # in STEREO ncc

# pc_align > [DSM]
[pc-align] # in STEREO dem-aligned

# point2dem > [DSM]
[point2dem] # in STEREO dem.tif

# dem_mosaic > [DSM]
[dem-mosaic] # in output dir
