name = "Name"
description = "Desc"
output = "."
dem = ""
src-folder = ""
pan-prefix = ""
pan-suffix = ""
ms-prefix = ""
ms-suffix = ""
cam-prefix = ""
cam-suffix = ""
mp-prefix = ""
mp-suffix = ""
# source = "smthg"
# source-header = true
pairs = "pairs.txt"
pairs-header = true
derive-pan = false
mp-pan = 0.7
mp-ms = 2

[[source]]
id = "id src" # ["id1", "id2"]
pan = ""
cam = ""
ms = ""
cam-ms = ""
mp = ""

# bundle_adjust > [MP]
[bundle-adjust] # BA

# mapproject > [MP]
[map-project] # MP/PAN / MP/MS

# gdal_translate > [MP]
[crop] # CROP

# gdal_pansharpening.py > [MP]
[pansharpening] # PANSHARP

# orbitviz > [MP]
[orbitviz] # ORB

# image_align > [PT]
[image-align] # ALIGNED

# parallel_stereo > [PT / DSM]
[stereo] # STEREO > PAIR
t = "pinhole"
individually-normalize = true
alignment-method = "none"
threads-multiprocess = 5
process = 5
no-bigtiff = true
tif-compress = "Deflate"
corr-kernel = [21, 21]
cost-mode = 2
stereo-algorithm = "asp_bm"
subpixel-mode = 2
subpixel-kernel = [35, 35]
stop-point = 5

# corr_eval > [PT]
[corr-eval] # in STEREO ncc

# pc_align > [DSM]
[pc-align] # in STEREO dem-aligned

# point2dem > [DSM]
[point2dem] # in STEREO dem.tif

# dem_mosaic > [DSM]
[dem-mosaic] # in output dir
