name = "Name"
description = "Desc"
output = "."
dem = ""
src_folder = ""
pan_prefix = ""
pan_suffix = ""
ms_prefix = ""
ms_suffix = ""
cam_prefix = ""
cam_suffix = ""
mp_prefix = ""
mp_suffix = ""
# source = "smthg"
# source-header = true
pairs = "pairs.txt"
pairs-header = true
derive-pan = false
force = true        # relaunch all
mp-pan = false
mp-ms = false

[[source]]
id = "id src"  # ["id1", "id2"]
pan = ""
ms = ""
cam = ""
mp = "path mp"

# bundle_adjust
[bundle-adjust] # BA

# gdal_translate
[crop] # CROP

# mapproject
[map-project-pan] # MP_PAN

# mapproject
[map-project-ms] # MP_MS

# gdal_pansharpening.py
[pansharpening] # PANSHARP

# orbitviz
[orbitviz] # ORB

# image_align
[image-align] # ALIGNED

# parallel_stereo
[stereo] # STEREO > PAIR
t = "pinhole"
individually-normalize = true
alignment-method = "none"
threads-multiprocess = 5
process = 5
no-bigtiff = true
tif-compress = "Deflate"
corr-kernel = [21, 21]
cost-mode = 2
stereo-algorithm = "asp_bm"
subpixel-mode = 2
subpixel-kernel = [35, 35]
stop-point = 5

# corr_eval
[corr-eval] # in STEREO ncc

# pc_align
[pc-align] # in STEREO dem-aligned

# point2dem
[point2dem] # in STEREO dem.tif

# dem_mosaic
[dem-mosaic] # in output dir
