name = "DSM Pleiades Preset"
description = ""
output = "."
dem = "dem"
src-folder = "/folder/source"
pairs = "pairs_dsm.txt"
mp-pan = 0.7

[[source]]
id = "img1"
pleiades = "f1/IMG_PHR_0/"

[[source]]
id = "img2"
pleiades = "f2/IMG_PHR_0/"

[[source]]
id = "img3"
pleiades = "f3/IMG_PHR_0/"

[[source]]
id = "img1_zone2"
pleiades = "f4/IMG_PHR_0/"

[[source]]
id = "img2_zone2"
pleiades = "f5/IMG_PHR_0/"

[[source]]
id = "img3_zone2"
pleiades = "f6/IMG_PHR_0/"

[bundle-adjust]
threads = 5

[map-project]
threads = 5
t_srs = "EPSG:XXXXX"

[stereo]
session-type = "pleiades"
threads-multiprocess = 5
stereo-algorithm = "asp_final_mgm"
cost-mode = 4
subpixel-mode = 11
corr-kernel = [7, 7]
subpixel-kernel = [5, 5]

[point2dem]
median-filter-params = [9, 50]
dem-hole-fill-len = 200
erode-length = 0
nodata-value = 0
tif-compress = "Deflate"
max-valid-triangulation-error = 2.0
remove-outlier-param = [75.0, 3.0]

[dem-mosaic]
