name = "Name"
description = "Desc"
output = "."
dem = "dem"
src-folder = "source"
pan-prefix = "IMG_P/IMG_"
pan-suffix = "-1.tif"
ms-prefix = "IMG_MS/IMG_"
ms-suffix = "-1.tif"
mp-pan = 0.7
mp-ms = 2

[[source]]
id = "date1"
pan = "pan1"
cam = "cam1.xml"
ms = "ms1"
cam-ms = "mscam"

[[source]]
id = "date2"
pan = "pan2"
cam = "cam2.xml"
ms = "ms2"
cam-ms = "mscam2"

[bundle-adjust]
threads = 5

[map-project]
threads = 5
t_srs = "EPSG:XXXXX"

[pansharpening]

[orbitviz]
