name = "Name"
description = "Desc"
output = "."
dem = "dem"
src_folder = "source"
pan_prefix = "IMG_"
pan_suffix = "-1.tif"
# pairs = "example/pairs.txt"
# pairs-header = true
derive-pan = true

[[source]]
id = "date1"
cam = "cam1.xml"
ms = "ms1"

[[source]]
id = "date2"
cam = "cam2.xml"
ms = "ms2"

[bundle-adjust]
d = true
dummy = "yummy"

[map-project]
d = true
dummy = "yummy"

[pansharpening]
some-option = true

[orbitviz]
dummy = "display me"
