name = "Name"
description = "Desc"
output = "."
src-folder = "/folder/source"
mp_prefix = "pref_"
mp_suffix = "_suff.file"
pairs = "pairs_pt.txt"

[[source]]
id = "date1"
mp = "mp1"

[[source]]
id = "date2"
mp = "mp2"

[stereo]
t = "nadirpinhole"
individually-normalize = true
alignment-method = "none"
threads-multiprocess = 5
process = 5
no-bigtiff = true
tif-compress = "Deflate"
corr-kernel = [9, 9]
cost-mode = 3
stereo-algorithm = "asp_final_mgm"
subpixel-mode = 11
subpixel-kernel = [5, 5]

[corr-eval]
