name = "Name"
description = "Desc"
output = "."
pairs = "example/pairs.txt"
pairs-header = true
src_folder = "raw_folder/"
pan_prefix = "pref_"
pan_suffix = "_suff.file"

# [[source]]

[stereo]
t = "nadirpinhole"
individually-normalize = true
alignment-method = "none"
threads-multiprocess = 5
process = 5
no-bigtiff = true
tif-compress = "Deflate"
corr-kernel = [9, 9]
cost-mode = 3
stereo-algorithm = "asp_mgm_final"
subpixel-mode = 11
subpixel-kernel = [5, 5]
stop-point = 5

[corr-eval]
