# ASPEO PARAMETER FILE V0.0.1
[aspeo]
name = "Name"
description = "Desc"
output = "."

[[source]]
id = "date"
# mp = "path mp"
prefix = "folder"
suffix = ".tif"
# camera
# raw

[stereo]
pairs = "pairs.txt"

[stereo.cmd]
t = "nadirpinhole"
individually-normalize = true
alignment-method = "none"
threads-multiprocess = 5
process = 5
no-bigtiff = true
tif-compress = "Deflate"
corr-kernel = [9, 9]
cost-mode = 3
stereo-algorithm = "asp_mgm_final"
subpixel-mode = 11
subpixel-kernel = [5, 5]
stop-point = 5
